### ISSUE TITLE
Not working on books

### ISSUE THREAD

**Issue by ghost** [phusitsom/kindle-cloud-reader-rpc#3]
Hello, the extension is working fine for the "browsing library" status, however, once i open a book my rich presence disappears.
here's the log of when i open kindle cloud > open a book:
127.0.0.1 - - [26/Apr/2024 14:24:08] "DELETE / HTTP/1.1" 200 -
127.0.0.1 - - [26/Apr/2024 14:24:08] "PUT / HTTP/1.1" 200 -
127.0.0.1 - - [26/Apr/2024 14:24:12] "DELETE / HTTP/1.1" 200 -

**Comment by lazykern** [comment]
Sorry for the late reply, I am a little busy right now but I will be checking this out ASAP.

**Comment by lazykern** [comment]
I've fixed it in the latest release
